### ISSUE TITLE
How to pass variables to command?

### ISSUE THREAD

**Issue by gutenye** [rsteube/carapace-spec#270]
Is there a way to pass positional arguments to a command? something like `['$(cmd1 $C_ARG0 $C_ARG1 $C_ARG2)']`

So that I can use an external command to do the dynamic completion.

**Comment by rsteube** [comment]
Actually, that's how it should work.
Maybe I've broken it at some point, will have a look.

**Comment by gutenye** [comment]
I tested again, and it worked this time!

**Comment by gutenye** [comment]
Is there a way to pass all args and flags at once? Like `['$(cmd1 $C_ARGS $C_FLAGS)']`?

**Comment by rsteube** [comment]
Just thought of that as well, but I think I haven't added it yet due to the word splitting issue (how to pass multiple args as variable).
Might need to rethink it a bit, this looks promising:
```sh
esh ❯ bash -c "echo one" -- two three
one
carapace-spec on  master [!] via 🐹 v1.22.0                                                                                             
esh ❯ bash -c "echo one $1" -- two three
one two
carapace-spec on  master [!] via 🐹 v1.22.0                                                                                             
esh ❯ bash -c "echo one $@" -- two three
one two three
```
